main/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings

from base_data_app.views import index, specialist, medical_services, doctor_reviews, \
    doctor_schedule, signup, profile_info, make_appointment, delete_appointment, get_med_records, \
    news_inner, news, ads, ads_inner, add_review, doctor_detail, doctor_service, get_ticket, delete_schedules

from users.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^login/$', auth_views.login, {'template_name': 'app/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout,{'template_name': 'app/logout.html'},  name='logout'),
    url(r'^profile/$', profile_info,  name='profile'),
    url(r'^profile/data/$', get_med_records,  name='get_med_records'),
    url(r'^doctors/$', specialist, name='doctors'),
    url(r'^doctors/(?P<pk>[0-9]+)$', doctor_detail, name='doctor_detail'),
    url(r'^doctors/(?P<pk>[0-9]+)/schedule/$', doctor_schedule, name='doctor_schedule'),
    url(r'^doctors/(?P<pk>[0-9]+)/reviews/$', doctor_reviews, name='doctor_reviews'),
    url(r'^doctors/(?P<pk>[0-9]+)/services/$', doctor_service, name='doctor_services'),
    url(r'^make_appointment/(?P<id>[0-9]+)/', make_appointment, name='make_appointment'),
    url(r'^delete_appointment/(?P<id>[0-9]+)/', delete_appointment, name='delete_appointment'),
    url(r'^services/$', medical_services, name='services'),
    url(r'^delete-schedules/$', delete_schedules, name='delete_schedules'),
    url(r'^news/$', news, name='news'),
    url(r'^news/(?P<id>[0-9]+)$', news_inner, name='news_inner'),
    url(r'^ads/$', ads, name='ads'),
    url(r'^ads/(?P<id>[0-9]+)$', ads_inner, name='ads_inner'),
    url(r'^add_review$', add_review, name='add_review'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^password/recovery/request/$', request_password_recovery, name='request_password_recovery'),
    url(r'^password/recovery/change/(?P<session_hash>[0-9A-Za-z_\-]+)$', show_set_password_form, name='show_set_password_form'),
    url(r'^ticket/(?P<appointment_id>[\w-]+)/$', get_ticket, name='get_ticket')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

news/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

specialists/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
from medical_app.models import Department, Schedules


class Profile(models.Model):
    class Meta:
        verbose_name = 'Пациент'
        verbose_name_plural = 'Пациенты'

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    inn = models.CharField(max_length=14, verbose_name='ИНН', null=True)
    card_id = models.IntegerField(verbose_name='Номер карточки', null=True)
    middle_name = models.CharField(max_length=255, verbose_name='Отчество', null=True)
    birthday = models.DateField(max_length=255, verbose_name='Дата рождения', null=True)
    assigned = models.BooleanField(verbose_name='Подтвержден', default=False)
    sex = models.IntegerField(verbose_name='Пол', null=True)
    department_id = models.ForeignKey(Department, to_field='department_id', null=True, verbose_name='Отделение')
    hospital = models.ForeignKey('medical_app.Hospital', verbose_name='Госпиталь', null=True, blank=True)

    def __str__(self):
        return str(self.user.username)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Appointment(models.Model):
    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

    appointment_id = models.CharField(verbose_name='ID записи', null=False, max_length=255)
    profile = models.ForeignKey(Profile)
    schedule = models.ForeignKey(Schedules)

ads/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

news/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

specialists/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

templates/app/ads_inner.html
{% extends 'base.html' %}

{% block content %}

<section class="medical_list_news inner uk-margin-medium-top">
    <div class="uk-container uk-container-small">
        <div class="uk-card-body bg-white ">
            <div class="uk-card uk-grid-collapse  uk-margin">
                <h1>{{ object.title }}</h1>
                {{ object.text|safe }}
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/app/deleted_schedules.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Удаление записей</title>
</head>
<body>
<h1>Записи удалены!</h1>
</body>
</html>

templates/app/login.html
{% extends 'base.html' %}

{% block content %}
    <section class="auch uk-margin-medium-top">
        <div class="uk-container uk-container-small">
            <div class="uk-card-body bg-white uk-flex-center" uk-grid>
                <form class=" uk-width-1-2@s" method="POST">
                    {% csrf_token %}
                    <fieldset class="uk-fieldset">

                        <legend class="uk-legend">Пожалуйста, авторизуйтесь:</legend>

                        <div class="uk-margin">
{#                            <p class="uk-margin-remove uk-form-danger">Название ошибки</p>#}
                            <label class="uk-form-label">Логин:</label>
                            <input class="uk-input" name="username" type="text" placeholder="">
                        </div>
                        <div class="uk-margin">
                            <label class="uk-form-label">Пароль:</label>
                            <input class="uk-input" name="password" type="password" placeholder="">
                        </div>

{#                        <div class="uk-margin uk-grid-small uk-child-width-auto uk-grid">#}
{#                            <label><input class="uk-checkbox" type="checkbox" checked> Запомнить меня на этом компьютере</label>#}
{#                        </div>#}
                        <div class="uk-margin">
                            <a href="{% url 'request_password_recovery' %}">Забыли свой пароль?</a>

                        </div>
                        <div class="uk-margin">
                            <a href="{% url 'signup' %}">Зарегистрироваться</a>
                        </div>
                        <div class="uk-margin uk-margin-medium-top">
                            <button type="submit" class="uk-button-default uk-button">Войти</button>
                        </div>

                    </fieldset>
                </form>
            </div>
        </div>
    </section>


{#    <form >#}
{#    {{ form }}#}
{#    </form>#}
{% endblock %}

templates/app/logout.html
{% extends 'base.html' %}

{% block content %}
    <section class="auch uk-margin-medium-top">
        <div class="uk-container uk-container-small">
            <div class="uk-card-body bg-white uk-flex-center" uk-grid>
                <form class=" uk-width-1-2@s" method="POST">
                    {% csrf_token %}
                    <fieldset class="uk-fieldset">

                        <legend class="uk-legend">Вы только что вышли!</legend>


                    </fieldset>
                </form>
            </div>
        </div>
    </section>


{#    <form >#}
{#    {{ form }}#}
{#    </form>#}
{% endblock %}

templates/app/news_inner.html
{% extends 'base.html' %}

{% block content %}

<section class="medical_list_news inner uk-margin-medium-top">
    <div class="uk-container uk-container-small">
        <div class="uk-card-body bg-white ">
            <div class="uk-card uk-grid-collapse  uk-margin">
                <h1>{{ object.title }}</h1>
                {{ object.text|safe }}
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/app/password_recovery_form.html
{% extends 'base.html' %}

{% block content %}
    <section class="auch uk-margin-medium-top">
        <div class="uk-container uk-container-small">
            <div class="uk-card-body bg-white uk-flex-center" uk-grid>
                <form class=" uk-width-1-2@s" method="POST">
                    {% csrf_token %}
                    <fieldset class="uk-fieldset">

                        <legend class="uk-legend">Придумайте пароль:</legend>

                        <div class="uk-margin">
{#                            <p class="uk-margin-remove uk-form-danger">Название ошибки</p>#}
                            <label class="uk-form-label">Новый пароль:</label>
                            <input class="uk-input" name="password" type="password" placeholder="">
                        </div>
                        <div class="uk-margin">
                            <label class="uk-form-label">Повторите:</label>
                            <input class="uk-input" name="re_password" type="password" placeholder="">
                        </div>

{#                        <div class="uk-margin uk-grid-small uk-child-width-auto uk-grid">#}
{#                            <label><input class="uk-checkbox" type="checkbox" checked> Запомнить меня на этом компьютере</label>#}
{#                        </div>#}
                        <div class="uk-margin">
                            <a href="{% url 'signup' %}">Зарегистрироваться</a>
                        </div>
                        <div class="uk-margin uk-margin-medium-top">
                            <button type="submit" class="uk-button-default uk-button">Сохранить и войти</button>
                        </div>

                    </fieldset>
                </form>
            </div>
        </div>
    </section>


{#    <form >#}
{#    {{ form }}#}
{#    </form>#}
{% endblock %}

templates/app/password_recovery_request.html
{% extends 'base.html' %}

{% block content %}
    <section class="auch uk-margin-medium-top">
        <div class="uk-container uk-container-small">
            <div class="uk-card-body bg-white uk-flex-center" uk-grid>
                <form class=" uk-width-1-2@s" method="POST">
                    {% csrf_token %}
                    <fieldset class="uk-fieldset">

                        <legend class="uk-legend">Введите свой E-Mail:</legend>

                        <div class="uk-margin">
                            <label class="uk-form-label">E-Mail:</label>
                            <input class="uk-input" name="email" type="email" placeholder=""{% if email %} value="{{ email }}" {% endif %}>
                        </div>

                        {% if message %}
                            <div class="uk-alert-success" uk-alert>
                                <a class="uk-alert-close" uk-close></a>
                                <p>{{ message }}</p>
                            </div>
                        {% endif %}

                        {% if error %}
                            <div class="uk-alert-danger" uk-alert>
                                <a class="uk-alert-close" uk-close></a>
                                <p>{{ error }}</p>
                            </div>
                        {% endif %}

                        <div class="uk-margin">
                            <a href="{% url 'login' %}">Авторизоваться</a>
                        </div>

                        <div class="uk-margin uk-margin-medium-top">
                            <button type="submit" class="uk-button-default uk-button">Отправить</button>
                        </div>

                    </fieldset>
                </form>
            </div>
        </div>
    </section>


{#    <form >#}
{#    {{ form }}#}
{#    </form>#}
{% endblock %}

templates/app/profile.html
{% extends 'base.html' %}
{% load days_tag %}


{% block content %}
    <div class="uk-container uk-container-small uk-margin-medium-top">
<p>Имя Фамилия: {{ user.first_name }} {{ user.last_name }}</p>
<p>Номер карточки: {{ profile.card_id }}</p>
<p>Номер ИНН: {{ profile.inn }}</p>
<p>Год рождения: {{ profile.birthday }}</p>
<p>Отделение: {{ profile.department_id.name }}</p>
    
    <table>
        <thead>
            <tr>
                <td>Идентификатор заказа</td>
                <td>Номер карточки</td>
                <td>Время</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            {% for item in profile.appointment_set.all %}
                <tr>
                    <td><a href="{% url 'get_ticket' appointment_id=item.appointment_id %}">{{ item.appointment_id }}</a></td>
                    <td>{{ item.profile.card_id }}</td>
                    {% format_date_time item.schedule.date item.schedule.time as dt %}
                    <td>{{ dt }}</td>
                    {% is_earlier_than_now item.schedule.time item.schedule.date as is_passed %}
                    <td>{% if not is_passed %}<button class="alert alert-danger deleteAppointmentBtn" data-url="{% url "delete_appointment" id=item.pk %}">Удалить запись</button>{% endif %}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
        <a href="{% url 'get_med_records' %}">Выписки врачей</a>
    </div>
{% endblock %}

{% block js %}
    {{ block.super }}

    <script>
        $('button.deleteAppointmentBtn').on('click', function(e) {
           e.preventDefault();

           var url = $(this).attr('data-url');

           if (confirm('Are you sure?')) {
               $.ajax({
                   method: 'POST',
                    url: url,
                   dataType: 'json',
                   success: function (data) {
                       if (data.info) {
                           alert('Appointment successfully deleted')
                       } else {
                           alert('Error on delete appointment');
                       }
                   },
                   error: function () {

                   }
               });
           }
        });
    </script>
{% endblock %}

templates/app/services_list.html
{% extends 'base.html' %}

{% block content %}
    <section class="crumbs">
{#    <div class="uk-container uk-container-small">#}
{#        <ul class="uk-breadcrumb">#}
{#            <li><a href="#">Главная страница</a></li>#}
{#            <li><a href="#">Item</a></li>#}
{#            <li class="uk-disabled"><a href="#">Disabled</a></li>#}
{#            <li><span href="#">Специалисты</span></li>#}
{#        </ul>#}
{#        <h3>Услуги и цены</h3>#}
{#    </div>#}
</section>
    <section class="specialist uk-margin-medium-top">
    <div class="uk-container uk-container-small">
        <div class="services">
{#            <h4>Терапевтическая косметология</h4>#}
            <ul>
                {% for service in services %}
                <li>{{ service.name }} <span class="uk-float-right">{{ service.price }} сом</span></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</section>
{% endblock %}

templates/app/specialist.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
{#    <section class="crumbs">#}
{#    <div class="uk-container uk-container-small">#}
{#        <ul class="uk-breadcrumb">#}
{#            <li><a href="#">Главная страница</a></li>#}
{#            <li><a href="#">Item</a></li>#}
{#            <li class="uk-disabled"><a href="#">Disabled</a></li>#}
{#            <li><span href="#">Специалисты</span></li>#}
{#        </ul>#}
{#        <h3>Название страницы</h3>#}
{#    </div>#}
{#</section>#}
<section class="specialist uk-margin-medium-top">
    <div class="uk-container uk-container-small">
        <div class="uk-grid uk-flex-middle" uk-grid>
            <div class="uk-width-1-5@m">
                <div class="img-wrapper">
                    <img src="{% if object.image %}{{ object.image.url }}{% else %}{% static 'img/png/noimage.png' %}{% endif %}" alt="">
                </div>
            </div>
            <div class="uk-width-expand@m uk-padding-remove uk-text-left@m uk-text-center">
                <h2>{{ object.last_name }} {{ object.fist_name }} {{ object.middle_name }}</h2>
                <span>{{ object.position }}</span>
            </div>
            <div class="uk-width-1-4@m uk-text-right@m uk-text-center">
                <a  href="{% url 'doctor_schedule' pk=object.id %}" class="uk-button-default uk-button recording_for_admission">Запись на приём</a>
            </div>
        </div>
        <ul class="uk-tab-bottom uk-tab" >
            {% url 'doctor_detail' pk=object.id as doctor_detil %}
            {% url 'doctor_schedule' pk=object.id as doctor_schedule %}
            {% url 'doctor_reviews' pk=object.id as doctor_reviews %}
            {% url 'doctor_services' pk=object.id as doctor_services %}
            <li {% if request.path == doctor_detil %}class="uk-active"{% endif %}><a href="{% url 'doctor_detail' pk=object.id %}">Образование и опыт работы</a></li>
            <li {% if request.path == doctor_schedule %}class="uk-active"{% endif %}><a href="{% url 'doctor_schedule' pk=object.id %}">Расписание</a></li>

            <li {% if request.path == doctor_reviews %}class="uk-active"{% endif %}><a href="{% url 'doctor_reviews' pk=object.id %}">Отзывы <span class="uk-badge">{{ reviews_count }}</span></a></li>
            <li {% if request.path == doctor_services %}class="uk-active"{% endif %}><a href="{% url 'doctor_services' pk=object.id%}">Услуги <span class="uk-badge">{{ services_count }}</span></a></li>
        </ul>

        <div class="education_work">
            {{ object.resume|safe }}
        </div>

    </div>
</section>
{% endblock %}

templates/app/specialist_reviews.html
{% extends 'base.html' %}

{% block content %}
{#<section class="crumbs">#}
{#    <div class="uk-container uk-container-small">#}
{#        <ul class="uk-breadcrumb">#}
{#            <li><a href="#">Главная страница</a></li>#}
{#            <li><a href="#">Item</a></li>#}
{#            <li class="uk-disabled"><a href="#">Disabled</a></li>#}
{#            <li><span href="#">Специалисты</span></li>#}
{#        </ul>#}
{#        <h3>Отзывы специалиста</h3>#}
{#    </div>#}
{#</section>#}
<section class="specialist uk-margin-medium-top">
    <div class="uk-container uk-container-small">

        {% include 'partials/specialist_info.html' with reviews_count=reviews.count %}

        <div class="uk-text-center uk-margin-medium-top">
            <a href="#bottom-scroll" class="uk-button uk-button-default add-comment" uk-scroll="offset: 60"><span class="uk-margin-small-right" uk-icon="icon: plus-circle"></span> Добавить отзыв</a>
        </div>
        <div id="comment-wrapper">
            {% for rev in reviews %}
                <article class="uk-comment uk-comment-primary">
                    <header class="uk-comment-header uk-grid-medium uk-flex-middle" uk-grid>
                        <div class="uk-width-expand">
                            <h4 class="uk-comment-title uk-margin-remove">{{ rev.name }}<span class="uk-float-right">{{ rev.created_at|date:"m.d.Y" }}</span></h4>
                        </div>
                    </header>
                    <div class="uk-comment-body">
                        <p>{{ rev.text }}</p>
                    </div>
                </article>
                <hr>
            {% endfor %}
        </div>
        <form action="{% url 'add_review' %}" id="bottom-scroll" method="POST">
            {% csrf_token %}
            <input type="hidden" value="{{ object.id }}" name="pk">
            <div class="uk-margin">
                <div class="">
                    <textarea class="uk-textarea" name="text" id="" cols="30" placeholder="Ваше сообщение" rows="10"></textarea>
                </div>
            </div>
            <div class="uk-margin">
                <button class="uk-button-default uk-button">Отправить</button>
            </div>
        </form>
    </div>
</section>
{% endblock %}

{% block js %}
    {{ block.super }}


    <script>
        $(document).ready(function () {
            var form = $('#bottom-scroll');
            form.on('submit', function (e) {
                e.preventDefault();
                var wrapper = $('#comment-wrapper');
                var data = {
                    text: form.find('textarea').val(),
                    pk: form.find('input[name="pk"]').val(),
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                };
                $.ajax({
                    url: form.attr('action'),
                    method: 'POST',
                    data: data,
                    dataType: 'JSON',
                    success: function (response) {
                        if(response.success) {
                            wrapper.append(response.message);
                            form.find('textarea').val('');
                            var reviews_count = $('#reviews-count');
                            var countVal = parseInt(reviews_count.html());
                            countVal++;
                            reviews_count.html(countVal);
                        } else {
                            UIkit.notification({
                                message: response.message,
                                status: 'danger',
                                pos: 'top-right',
                                timeout: 5000
                            });
                        }
                    }
                });
            });
        });
    </script>
{% endblock %}

templates/app/specialist_services.html
{% extends 'base.html' %}
{% block content %}
    {#<section class="crumbs">#}
    {#    <div class="uk-container uk-container-small">#}
    {#        <ul class="uk-breadcrumb">#}
    {#            <li><a href="#">Главная страница</a></li>#}
    {#            <li><a href="#">Item</a></li>#}
    {#            <li class="uk-disabled"><a href="#">Disabled</a></li>#}
    {#            <li><span href="#">Специалисты</span></li>#}
    {#        </ul>#}
    {#        <h3>Услуги специалиста</h3>#}
    {#    </div>#}
    {#</section>#}
    <section class="specialist uk-margin-medium-top">
        <div class="uk-container uk-container-small">
            {% include 'partials/specialist_info.html' %}
            {% for s in med_service %}
                <div class="services">
                    <h4>{{ s.title }}</h4>
                    <ul>
                        <li><a href="#">{{ s.medical_service.name }}
                                <span class="uk-float-right">{{ s.medical_service.price }}сом</span></a></li>
                    </ul>
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

templates/app/specialists_list.html
{% extends 'base.html' %}
{% load staticfiles days_tag %}
{% block content %}
{#<section class="crumbs">#}
{#    <div class="uk-container uk-container-small">#}
{#        <ul class="uk-breadcrumb">#}
{#            <li><a href="#">Главная страница</a></li>#}
{#            <li><a href="#">Item</a></li>#}
{#            <li class="uk-disabled"><a href="#">Disabled</a></li>#}
{#            <li><span href="#">Специалисты</span></li>#}
{#        </ul>#}
{#        <h3>Специалисты</h3>#}
{#    </div>#}
{#</section>#}
<section class="specialist_list uk-margin-medium-top">
    <div class="uk-container uk-container-small">
        <form>
            <div class="uk-grid uk-child-width-1-2@s uk-child-width-1-3@m" uk-grid>
                <div class="">
                    <select  class="select-specialist" placeholder="Все клиники" id="hospital_filter">
                        <option value></option>
                        {% for op in hospitals %}
                            <option value="{{ op.hospital_id }}"{% if hospital_id == op.hospital_id %} selected{% endif %}>{{ op.name }}</option>
                        {% endfor %}
                    </select>
                </div>
{#                <div class="search uk-width-expand">#}
{#                    <input class="uk-input" type="text" placeholder="Фамилия, имя или отчество">#}
{#                    <button class="uk-button uk-button-default" type="submit">Поиск</button>#}
{#                </div>#}
            </div>
        </form>
        <div class="uk-grid uk-grid-small uk-child-width-1-3@m uk-child-width-1-2@s uk-margin-medium-top" uk-grid>
            {% for doctor in doctors %}
            <div class="item">
                <div class="uk-card uk-card-default uk-box-shadow-hover-xlarge">
                    <a href="" class="commenting" title="Отзывы специалиста" uk-tooltip>
                        <span  uk-icon="icon:  commenting"></span>
                        1
                    </a>
                    <div class="uk-card-media-top">
                        <a href="{% url 'doctor_detail' pk=doctor.id %}"><img src="{% if doctor.image %}{{ doctor.image.url }}{% else %}{% static 'img/png/noimage.png' %}{% endif %}" alt=""></a>
                    </div>
                    <div class="uk-card-body">
                        <h2 class="uk-card-title uk-text-center uk-margin-remove"><a href="{% url 'doctor_detail' pk=doctor.id %}">
                            {{ doctor.last_name }} {{ doctor.fist_name }} {{ doctor.middle_name }}</a></h2>
                        <span class="prof uk-display-block uk-text-center">{{ doctor.position }}</span>
                        <div class="date uk-text-center">
                            <span>Пн</span>
                            <span>Вт</span>
                            <span>Ср</span>
                            <span>Чт</span>
                            <span>Пт</span>
                            <span>Сб</span>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <ul class="uk-pagination uk-margin-medium-top uk-flex-center" uk-margin>
            {% if doctors.has_previous %}
                <li><a href="{% prepare_url request.get_full_path 'page' %}page={{ doctors.prev_page_number }}"><span uk-pagination-previous></span></a></li>
            {% endif %}
            <li>Страница {{ doctors.number }} из {{ doctors.paginator.num_pages }}</li>
            {% if doctors.has_next %}
                 <li><a href="{% prepare_url request.get_full_path 'page' %}page={{ doctors.next_page_number }}"><span uk-pagination-next></span></a></li>
            {% endif %}
        </ul>
    </div>
</section>
{% endblock %}

{% block js %}
    {{ block.super }}

    <script>
        $(document).ready(function () {
            var select = $('#hospital_filter');


            select.on('change', function () {
                var value = $(this).val();
                //console.log(prepareUrl(document.location.href, 'hospital') + 'hospital=' + value);
                window.location.href = prepareUrl(document.location.href, 'hospital') + 'hospital=' + value
            });

            function prepareUrl(url, param) {
                if(url.includes('?')) {
                    b = url.split('?')[0];
                    url = url.split('?')[1];
                    if(url.includes('&')) {
                        var params = url.split('&');
                        var index = -1;
                        for(var i=0; i < params.length; ++i) {
                            var k = params[i].split('=')[0];
                            if (k === param) {
                                index = i;
                                break;
                            }
                        }

                        if(index > -1) {
                            var new_url = '';
                            for(var s=0; s < params.length; ++s) {
                                if (index !== s) {
                                    new_url += new_url !== '' ? params[i] : '&' + params[i];
                                }
                            }
                            return b + '?' + new_url + '&';
                        }
                        return b + '?' + url + '&'
                    } else {
                        if(url.includes('=')) {
                            var _k = url.split('=')[0];
                            if(_k === param) {
                                return b + '?';
                            } else {
                                return b + '?' + url + '&';
                            }
                        }
                        return b + '?';
                    }
                }
                return url + '?';
            }
        });
    </script>
{% endblock %}

templates/app/ticket_print.html
<html>
<head>
    <title>Талон</title>
</head>

<body>
<table>
    <tbody>
    <tr>
        <td>Имя пациента</td>
        <td><b>{{ name }}</b></td>
    </tr>
    <tr>
        <td>Дата</td>
        <td><b>{{ s_date }}</b></td>
    </tr>
    <tr>
        <td>Время</td>
        <td><b>{{ time }}</b></td>
    </tr>
    <tr>
        <td>Врач</td>
        <td><b>{{ doctor_name }}</b></td>
    </tr>
    </tbody>
</table>


<script>
    window.print();
</script>
</body>
</html>